name: Install pnpm
description: Installs pnpm along with pnpm dependencies. Cached.

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10.8.0

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: "pnpm"

    - name: Install dependencies
      run: pnpm install
      shell: bash
