name: Verify pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: ./.github/actions/install-dotnet

      - name: Install pnpm
        uses: ./.github/actions/install-pnpm

      - run: pnpm build

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: ./.github/actions/install-pnpm

      - run: pnpm lint

  resharper:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: ./.github/actions/install-dotnet

      - name: Install pnpm
        uses: ./.github/actions/install-pnpm

      - run: pnpm scripts#resharper
