name: Verify pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-pnpm

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          cache: true
          cache-dependency-path: ./apps/api/packages.lock.json

      - run: pnpm build

  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/install-pnpm

      - run: pnpm lint
